# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 575)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(70, 130, 251, 261))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.subject_line = QtWidgets.QLineEdit(Dialog)
        self.subject_line.setGeometry(QtCore.QRect(70, 80, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.subject_line.setFont(font)
        self.subject_line.setInputMask("")
        self.subject_line.setText("")
        self.subject_line.setMaxLength(32767)
        self.subject_line.setObjectName("subject_line")
        self.list_of_students = QtWidgets.QListWidget(Dialog)
        self.list_of_students.setGeometry(QtCore.QRect(360, 180, 256, 192))
        self.list_of_students.setObjectName("list_of_students")
        self.email_button = QtWidgets.QPushButton(Dialog)
        self.email_button.setGeometry(QtCore.QRect(70, 430, 121, 51))
        self.email_button.setStyleSheet("background-color: cyan")
        self.email_button.setObjectName("email_button")
        self.update_db_button = QtWidgets.QPushButton(Dialog)
        self.update_db_button.setGeometry(QtCore.QRect(220, 430, 121, 51))
        self.update_db_button.setStyleSheet("background-color: yellow;")
        self.update_db_button.setObjectName("update_db_button")
        self.unpaid_student_button = QtWidgets.QPushButton(Dialog)
        self.unpaid_student_button.setGeometry(QtCore.QRect(370, 430, 121, 51))
        self.unpaid_student_button.setStyleSheet("background-color: gray")
        self.unpaid_student_button.setObjectName("unpaid_student_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mailing List"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "Body"))
        self.subject_line.setPlaceholderText(_translate("Dialog", "subject"))
        self.email_button.setText(_translate("Dialog", "Email"))
        self.update_db_button.setText(_translate("Dialog", "Update DB"))
        self.unpaid_student_button.setText(_translate("Dialog", "Unpaid Students"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
